export const prompts = [
  "Play on one string",
  "Only 16th notes",
  "Only triplets",
  "Only triads",
  "Play on the E and B strings",
  "Reverse the structure",
  "Think of the radio",
  "Think of the mountains",
  "Play dramatically",
  "What would your closest friend do?",
  "Highlight flaws",
  "Emphasize repetitions",
  "Take a break",
  "Listen to the quiet voice",
  "Use fewer notes",
  "Consider transitions",
  "Change the rhythm",
  "Make a sudden change",
  "Repeat a mistake",
  "Simplify",
  "Add an unexpected element",
  "Embrace errors",
  "Work at a different speed",
  "Listen to your environment",
  "Alter the tempo",
  "Use a sound you dislike",
  "Go to an extreme, then get comfortable",
  "Openly resist what you're inclined to do",
  "Turn it upside down",
  "What would your mentor would do?",
  "Remove specifics, convert to ambiguities",
  "Use unorthodox techniques",
  "Balance consistency with inconsistency",
  "Use silence",
  "Focus on the negative space",
  "Break the rules",
  "Explore a single note",
  "Only natural harmonics",
  "Use finger tapping",
  "Only open strings",
  "Practice string skipping",
  "Write a melody on the top three strings",
  "Transpose a melody to a different position on the neck",
  "Use a backing track in an unfamiliar genre",
  "Play smooth",
  "Play fingerstyle",
  "Only chord tones",
  "Create a walking bass line on the lower strings",
  "Swap the groove from straight to swing",
  "Restrict to a single fret",
  "Play in octaves",
  "Use a looper",
  "Use only the G string",
  "Play backwards",
  "Only string bending",
  "Only 12th fret and above",
  "Only power chords",
  "Use a slide on one string",
  "Pick percussively",
  "Imitate a saxophone",
  "Practice tremolo picking on each string",
  "Follow the contour of a spoken phrase",
  "Mute with the picking hand",
  "Use a new pedal or effect",
  "Record yourself, critique timing and expression",
  "Explore dynamics",
  "Play a lick in many positions",
  "Call and response within a solo",
  "Vibrato on long-held notes",
  "Only muted strings",
];
