export const prompts = [
  "Play on one string",
  "Play in 16th notes",
  "Play in triplets",
  "Play triads",
  "Reverse the structure",
  "Think of the radio",
  "Use an old idea",
  "What would your closest friend do?",
  "Highlight flaws",
  "Emphasize repetitions",
  "Take a break",
  "Listen to the quiet voice",
  "Use fewer notes",
  "Consider transitions",
  "Change the rhythm",
  "Make a sudden change",
  "Repeat a mistake",
  "Simplify",
  "Add an unexpected element",
  "Embrace errors",
  "Work at a different speed",
  "Listen to your environment",
  "Alter the tempo",
  "Use a sound you dislike",
  "Go to an extreme, move back to a more comfortable place",
  "Openly resist what you're inclined to do",
  "Turn it upside down",
  "What would your mentor would do?",
  "Remove specifics, convert to ambiguities",
  "Use unorthodox techniques",
  "Balance consistency with inconsistency",
  "Use silence",
  "Focus on the negative space",
  "Break the rules",
  "Explore a single note",
  "Improvise using only natural harmonics",
  "Incorporate finger tapping into a chord progression",
  "Create a riff using only open strings",
  "Practice string skipping with a scale pattern",
  "Play a solo using only the pentatonic scale",
  "Write a melody on the top three strings",
  "Transpose a melody to a different position on the neck",
  "Improvise over a backing track in an unfamiliar genre",
  "Play smooth",
  "Play fingerstyle",
  "Experiment with alternate tunings",
  "Improvise using only chord tones",
  "Create a walking bass line on the lower strings",
  "Practice hybrid picking with an etude",
  "Compose a piece using only artificial harmonics",
  "Swap the groove of a song from straight to swing",
  "Restrict your improvisation to a single fret",
  "Play in octaves",
  "Use a looper pedal to build a complete song layer by layer",
  "Use only the G string",
  "Play backwards",
  "Only string bending",
  "Only 12th fret and above",
  "Only power chords",
  "Use a slide on one string",
  "Pick percussively",
  "Imitate a saxophone",
  "Practice tremolo picking on each string",
  "Write a melodic line that follows the contour of a spoken phrase",
  "Mute with the picking hand",
  "Use a new pedal or effect",
  "Record yourself and critique your timing and expression",
  "Explore dynamics",
  "Play a lick in many positions",
  "Call and response within a solo",
  "Vibrato on long-held notes",
  "Only muted strings",
];
